### ISSUE TITLE
Fuzzy Section Attribute Editor

### ISSUE THREAD

**Issue by mahotilo** [juek/BackgroundComposer#1]
With BackgroundComposer installed I have such fuzzy Section Attribute Editor. Can you see this?

![image](https://user-images.githubusercontent.com/14929385/77894461-fbd8f680-727d-11ea-9ae1-12d0b846be7c.png)

**Comment by juek** [comment]
I can't see a difference here, not even in Opera.

**Comment by juek** [comment]
Does it really go away when you uninstall Background Composer?

**Comment by juek** [comment]
Opera generally seems to blur fonts a bit compared to Firefox (no sub-pixel sampling):

![grafik](https://user-images.githubusercontent.com/704283/77937226-52612780-72b4-11ea-9679-e63bd5c29e0f.png)

**Comment by mahotilo** [comment]
> Does it really go away when you uninstall Background Composer?

Yes.
I checked in private mode without plugins - same result.
It looks more like jitter. I have tried to delete css styles step by step and caught a moment when jitter begins only after clicking on Back.Composer

**Comment by mahotilo** [comment]
Honestly, I have seen this since the plugin was only on the forum. But I thought it was a childhood illness.

**Comment by mahotilo** [comment]
You can see that only attributes editor is affected 
![image](https://user-images.githubusercontent.com/14929385/77938399-5b56f680-72be-11ea-859d-5685ad29e389.png)
I deleted #gp_admin_box1

This is a picture after removing the plugin.
![image](https://user-images.githubusercontent.com/14929385/77938590-a3761900-72be-11ea-92aa-b1393a2f11c0.png)

**Comment by mahotilo** [comment]
The main problem is that you can not reproduce the issue :(

**Comment by mahotilo** [comment]
Well. Seems it is conflict with another plugin. Wil turn they one by one.

**Comment by mahotilo** [comment]
When I open Devtools jitter disappears!

It seems to me, the source is not some kind of plugin but the number of the installed plugins.

**Comment by mahotilo** [comment]
It is not plugin. It is theme.
With `Bootswatch_Scss` jitter is almost invisible and appears only when BackComp. DIV is shown/hidden. But with `Bootswatch 4 Scss` it is clearly (actually, fuzzy:) visible right after BackComp. DIV is shown.

**Comment by mahotilo** [comment]
I think it has something to do with JS.

**Comment by juek** [comment]
From a little googling it seems that Opera has a history of blurry text now and then, mostly with CSS translate stuff and GPU hardware acceleration. The new fixed gpabox uses translate to center itself horizontally.

**Comment by mahotilo** [comment]
Hm, you are right. When I switch off #gp_admin_box{transform: translateX(-50%);} the fuzziness disappears.
But what so special happens when I click to open the BackgroundComposer?
My Opera has no problems with #gp_admin_box{transform: translateX(-50%);} without this plugin, which is very handy in other aspects.

Edit
And, as I said, issue relates to BS4

**Comment by mahotilo** [comment]
I have found the source of the problem and made a PR https://github.com/juek/BackgroundComposer/pull/2.
